# auth = Auth(db,cas_provider = 'http://127.0.0.1:3000/merch_erp/default/user/cas')
# db = DAL('mssql4://username:password@localhost/test', pool_size=0)

db = DAL('postgres://root:admin@localhost:5432/mpc_inv', pool_size=0)
# Field('division_id', 'reference division', readable = False, writable = False, requires = IS_IN_DB(db, db.division.id, '%(division)s', zero = 'Choose division')),
# Field('division', requires = IS_UPPER(), label = 'Division'),format = '%(division)s')
db.define_table('Division',
    Field('Div_Code','string', length = 5),
    Field('Div_Name','string', length = 25), format = '%(Div_Code)s')

db.define_table('Department',
    Field('Div_Code_Id', 'reference Division', requires = IS_IN_DB(db, db.Division.id,'%(Div_Code)s', zero = 'Choose Division')),
    Field('Dept_Code','string'),
    Field('Dept_Name','string'))

db.define_table('Product',
    Field('Dept_Code_Id','reference Department', requires = IS_IN_DB(db, db.Department.id,'%(Dept_Code)s', zero = 'Choose Department')),
    Field('Product_Code','string'),
    Field('Product_Name', 'string'))

db.define_table('SubProduct',
    Field('Product_Code_Id','reference Product', requires = IS_IN_DB(db, db.Product.id, '%(Product_Code)s', zero = 'Choose Product Code')),
    Field('Subproduct_Code','string'),
    Field('Subproduct_Name','string'))

db.define_table('GroupLine',
    Field('Group_Line_Code','string',length=7),
    Field('Group_Line_Name', 'string', length=50))

db.define_table('Brand_Line',
    Field('Group_Line_Code_Id','reference GroupLine', requires = IS_IN_DB(db, db.GroupLine.id, '%(Group_Line_Code)s', zero = 'Choose Group Line')),
    Field('Brand_Line_Code','string',length=8),
    Field('Brand_Line_Name','string',length=50))

db.define_table('Brand_Classification',
    Field('Brand_Line_Code_Id','reference Brand_Line', requires = IS_IN_DB(db, db.Brand_Line.id, '%(Brand_Line_Code)s', zero= 'Choose Brand Line')),
    Field('Brand_Cls_Code','string', length=8),
    Field('Brand_Cls_Name','string',length=50))

db.define_table('Item_Status',
    Field('Item_Status_Code','string',length=5),
    Field('Item_Status_Type','string',length=15))

db.define_table('Fragrance_Type',
    Field('Product_Code_Id','reference Product', requires = IS_IN_DB(db, db.Product.id, '%(Product_Code)s', zero = 'Choose Product Code')),
    Field('Fragrance_Code','string',length=6),
    Field('Fragrance_Name','string',length=35))

db.define_table('Item_Color',
    Field('Color_Code','string',length=5),
    Field('Color_Name','string',length=25))

db.define_table('Item_Size',
    Field('Size_Code','string',length=10),
    Field('Size_Name','string',length=25))

db.define_table('Item_Collection',
    Field('Collection_Code','string',length=5),
    Field('Collection_Name','string',length=25))

db.define_table('Made_In',
    Field('Made_In_Name','string', length=30))

db.define_table('Section',
    Field('Section_Code','string',length=5),
    Field('Section_Name','string',length=15))

db.define_table('itemmas',
    Field('Item_Code', 'string', length = 10, label = 'Item Code',requires = IS_NOT_IN_DB(db, 'itemmas.Item_Code')),
    Field('Ref_No', 'string', length = 15, label = 'Reference No',requires = IS_NOT_IN_DB(db, 'itemmas.Ref_No')),
    Field('Section_Code', 'string', length = 15),
    Field('Supplier_Item_Ref', 'string', length = 15),
    Field('Item_Description', 'string', length = 35, label = 'Description'),
    Field('Supp_Code', 'string', length = 8),
    Field('Mr_Cost', 'decimal(10,2)'),
    Field('Ave_Cost', 'decimal(10,2)'),
    Field('Mr_Lndcost', 'decimal(10,2)', ),
    Field('Currency', 'string', length = 5),
    Field('Size_Code', 'string', length = 10),
    Field('UOM', 'integer'),
    Field('Supp_OUM', 'integer'),
    Field('Op_Avcost', 'decimal(10,2)'),
    Field('Last_Issdt', 'date'),
    Field('Price_Wsch', 'decimal(10,2)', label = 'Price'),
    Field('Price_Rtch', 'decimal(10,2)'),
    Field('Price_Vnch', 'decimal(10,2)'),
    Field('Created_On', 'date'),
    Field('Created_By', 'date'),
    Field('Reorder_Qty', 'integer'),
    Field('Bar_Code', 'string', length = 20),
    Field('Dept_Code', 'string'),
    Field('Product_Code','string'),
    Field('Sub_Product_Code','string'),
    Field('Group_Line_Code','string'),
    Field('Brand_Line_Code','string'),
    Field('Brand_Cls_Code','string'),
    Field('Gender_Code','string'),
    Field('Item_Status_Code','string'),
    Field('Fragrance_Code','string'),
    Field('Color_Code','string'),
    Field('Size_Code','string'),
    Field('Collection_Code','string'),
    Field('Made_In','string'))


# db.define_table('acctmas',
#     Field('Acct_Code', 'string', length = 8),
#     Field('Groupname', 'string', length = 20),
#     Field('Bs_Code', 'string', length =	15),
#     Field('Bs_Code1', 'string', length = 15),
#     Field('Name','string', length =	45),
#     Field('Addrs1',	'string', length = 35),
#     Field('Addrs2', 'string', length = 35),
#     Field('Addrs3',	'string', length = 35),
#     Field('Addrs4', 'string', length = 35),
#     Field('City_Town', 'string', length = 35),
#     Field('Country', 'string', length =	35),
#     Field('Email1', 'string', length = 35),
#     Field('Email2',	'string', length = 35),
#     Field('Web1', 'string', length = 35),
#     Field('Zip_Code', 'string', length = 12),
#     Field('Tel_No1', 'string', length = 16),
#     Field('Tel_No2', 'string', length = 16),
#     Field('Acts_Telno', 'string', length = 12),
#     Field('Contact1', 'string',	length = 20),
#     Field('Grade', 'string', length = 10),
#     Field('Benefe', 'string', length = 45),
#     Field('Bankers', 'string', length = 45),
#     Field('Bad1', 'string',	length = 45),
#     Field('City', 'string',	length = 45),
#     Field('Sort_Code', 'string', length = 25),
#     Field('Bnk_Code', 'string', length = 25),
#     Field('Currency', 'string',	length = 20),
#     Field('Contact2', 'string',	length = 20),
#     Field('Acc_Nbr', 'string',	length = 45),
#     Field('Crt_Bal1', 'integer'),
#     Field('Opn_Bal1', 'decimal(10,2)'),
#     Field('Opn_Dte', 'date'),
#     Field('Last_Updte', 'date'),
#     Field('Status', 'string', length = 10),
#     Field('Crt_Limit', 'integer'),
#     Field('Ac_Op_Dte', 'date'),
#     Field('Agr_Dte', 'date'),
#     Field('Sp_Name', 'string', length = 45),
#     Field('Id_Date', 'date'),
#     Field('Paymt_Trms', 'string', length = 45),
#     Field('Trms_Dep1', 'integer'),
#     Field('Cat_Dep1', 'string',	length = 6),
#     Field('Agrement', 'boolean'),
#     Field('Agr_Date', 'date'),
#     Field('Sponsor', 'string', length = 30),
#     Field('Sp_Idno', 'string', length = 20),
#     Field('Id_Dte', 'date'),
#     Field('Id_Expdt', 'date'),
#     Field('Remarks', 'string', length = 35),
#     Field('Collector', 'string', length = 35),
#     Field('Budget',	'decimal(10,2)'),
#     Field('Letterctr', 'integer'),
#     Field('Lettersw', 'integer'),
#     Field('Active',	'boolean'),
#     Field('Group1',	'string', length = 15),
#     Field('Tgrade',	'string', length = 1),
#     Field('Acc_Name', 'string',	length = 25),
#     Field('Gm_Name', 'string', length = 25),
#     Field('Gm_Tel',	'string', length = 10),
#     Field('Pur_Name', 'string',	length = 25),
#     Field('Pur_Tel', 'string', length = 10),
#     Field('Mvno', 'integer'),
#     Field('Cr_L1', 'integer'),
#     Field('Cr_Days', 'integer'),
#     Field('Mflag', 'boolean'),
#     Field('Trn_Type', 'integer'),
#     Field('Group', 'string', length = 15))

# db.define_table('brandmas',
#     Field('Supp_Code', 'string', length = 8),
#     Field('Supp_Name', 'string', length = 35),
#     Field('Brand_Code', 'string', length = 4),
#     Field('Brand_Cod2', 'string', length = 10),
#     Field('Brand_Line', 'string', length =	30),
#     Field( 'Lines', 'string', length =	30),
#     Field( 'Brandgroup', 'string', length =	30),
#     Field( 'Group', 'string', length = 25),
#     Field( 'Maingroup', 'string', length = 30),
#     Field( 'Ib', 'integer'),
#     Field( 'Tgt_Qtr1', 'integer'),
#     Field( 'Tgt_Qtr2', 'integer'),
#     Field( 'Tgt_Qtr3', 'integer'),
#     Field( 'Tgt_Qtr4', 'integer'),
#     Field( 'Trg_Tot', 'integer'),
#     Field( 'Sup_Trg', 'integer'),
#     Field( 'Rgroup', 'string', length =	25),
#     Field( 'Tgroup', 'string', length =	25),
#     Field( 'Rankgrp', 'string', length = 25),
#     Field( 'Lineflag', 'boolean'),
#     Field( 'Product', 'string', length = 45),
#     Field( 'Grouplines', 'string', length =	60),
#     Field( 'Br_Lines', 'string', length = 60),
#     Field( 'Br_Class', 'string', length = 60),
#     Field( 'Itsub_Type', 'string', length =	60))

# db.define_table('trnmas',
#     Field('Location', 'integer'),
#     Field('Type', 'integer'),
#     Field('Dte', 'date'),
#     Field('Vouno', 'integer'),
#     Field('Ref_No', 'string', length = 15),
#     Field('Price_Cost', 'decimal(10,2)'),
#     Field('Qty', 'integer'),
#     Field('Units', 'integer'),
#     Field('Catagory', 'string', length = 1),
#     Field('Dflag', 'string', length = 1),
#     Field('Av_Cost', 'decimal(10,2)'),
#     Field('Ws_Cost', 'decimal(10,2)'),
#     Field('Rt_Cost', 'decimal(10,2)'),
#     Field('Sale_Cost', 'decimal(10,2)'),
#     Field('Sup_Cus', 'string', length = 8),
#     Field('Supp_Code', 'string', length = 8),
#     Field('Brand_Code', 'string', length = 4),
#     Field('Ref_No2', 'string', length = 15),
#     Field('Entrydte', 'date'),
#     Field('Saleman', 'string', length =	10))

# db.define_table('trnvou',
#     Field('Location', 'integer'),
#     Field('Type', 'integer'),
#     Field('Dte', 'date'),
#     Field('Vouno', 'integer'),
#     Field('Supp_Custm', 'string', length = 8),
#     Field('Totamount', 'decimal(10,2)'),
#     Field('Discount', 'integer'),
#     Field('Disc_Added', 'decimal(10,2)'),
#     Field('Other_Chrg', 'integer'),
#     Field('Order_Ref', 'integer'),
#     Field('Lc_No', 'integer'),
#     Field('Invno', 'string', length = 10),
#     Field('Exch_Rate', 'integer'),
#     Field('Lnd_Rate', 'integer'),
#     Field('Creditcode', 'integer'),
#     Field('Sales_Man', 'string', length = 10),
#     Field('Spare', 'string', length = 10),
#     Field('Stvdestin', 'integer'),
#     Field('Ordtype', 'integer'),
#     Field('Order_Ref2', 'string', length = 8),
#     Field('Entrydte', 'date'),
#     Field('Client', 'string', length = 30),
#     Field('Card', 'string', length = 35),
#     Field('Order_Ref3', 'string', length = 8),
#     Field('Address', 'string', length = 35),
#     Field('Tel', 'string', length = 15))
